services:
  postgres:
    image: postgres:17-alpine
    container_name: rwe-postgres
    environment:
      POSTGRES_DB: rwe_db
      POSTGRES_USER: rwe_user
      POSTGRES_PASSWORD: rwe_password
    ports:
      - "5432:5432"
    volumes:
      - rwe_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: rwe-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rwe-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  rwe_postgres_data:
