services:
  postgres:
    image: postgres:17-alpine
    container_name: rwe-postgres
    environment:
      POSTGRES_DB: rwe_db
      POSTGRES_USER: rwe_user
      POSTGRES_PASSWORD: rwe_password
    ports:
      - "5432:5432"
    volumes:
      - rwe_postgres_data:/var/lib/postgresql/data

volumes:
  rwe_postgres_data:
